//
//  TermsAndConditionsViewController.m
//  Reeel
//
//  Created by Paul Dariye on 4/29/15.
//  Copyright (c) 2015 colp. All rights reserved.
//

#import "TermsAndConditionsViewController.h"

@interface TermsAndConditionsViewController ()

@end

@implementation TermsAndConditionsViewController

- (instancetype)initWithCoder:(NSCoder *)coder
{
    self = [super initWithCoder:coder];
    if (self) {
        [self initializeForm];
    }
    return self;
}

- (instancetype)init
{
    self = [super init];
    if (self) {
        [self initializeForm];
    }
    return self;
}

- (void)initializeForm
{
    XLFormDescriptor *form;
    XLFormSectionDescriptor *section;
    
    form = [XLFormDescriptor formDescriptorWithTitle:@"Terms & Conditions"];
    
    section = [XLFormSectionDescriptor formSection];
    section.footerTitle = @"\t\t\tTerms and Conditions ('Terms') \n\n Last updated: May 06, 2015 \n\n \t Please read these Terms and Conditions ('Terms', 'Terms and Conditions') carefully before using the Reeel website (the 'Service') operated by Reeel ('us', 'we', or 'our'). \n \t Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service. \n \t By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service. \n \t Links To Other Web Sites Our Service may contain links to third-party web sites or services that are not owned or controlled by Reeel. \n \t Reeel has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Reeel shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services. \n \t We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit. \n \t\t\t\t Termination \n We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. \n \t All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. \n \t\t\t\t Governing Law \n These Terms shall be governed and construed in accordance with the laws of New York, United States, without regard to its conflict of law provisions. \n \t Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service. \n \t\t\t\t Changes \n \t We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 15 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. \n \t By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service. \n \t Our Terms and Conditions agreement was generated by TermsFeed Generator (https://termsfeed.com). \n \t\t\t\t Contact Us \n \t If you have any questions about these Terms, please contact us.";
    [form addFormSection:section];
    
    self.form = form;
    
}

- (void)viewDidLoad {
    [super viewDidLoad];
    
    // Do any additional setup after loading the view from its nib.
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

/*
#pragma mark - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    // Get the new view controller using [segue destinationViewController].
    // Pass the selected object to the new view controller.
}
*/

- (NSUInteger)supportedInterfaceOrientations
{
    return UIInterfaceOrientationMaskPortrait;
}

@end
